language: node_js
node_js:
  "9"
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo mysql -u root -e "CREATE USER IF NOT EXISTS 'travis'@'localhost' IDENTIFIED BY 'TRAVIS';";
  - sudo mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
  - sudo service mysql restart
install:
  - npm install
before_script:
  - "mysql -e 'create database test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
script:
  - npm test
after_failure:
  - "mysql -e 'show databases;'"
  - "cat ./config/database.yml"
